checkpoint: ./trained_models/DDG_RDE_Network_30k.pt
pdb: ./data/7FAE_RBD_Fv.pdb
mutations:
# H-CDR1
- GH26*
- YH27*
- TH28*
- FH29*
- TH30*
- TH31*
- YH32*
# H-CDR2
- NH52*
- AH53*
- GH54*
- NH55*
- GH56*
- NH57*
# H-CDR3
- GH99*
- GH100*
- GH101*
- RH102*
- RH103*
- LH104*
- QH105*
- FH106*
- DH107*
- YH108*
- FH109*
- DH110*
- YH111*
interest:
- TH31W
- AH53F
- NH57L
- RH103M
- LH104F
